### ISSUE TITLE
prefix "lc"

### ISSUE THREAD

**Issue by birgitstrackenbrock** [birgitstrackenbrock/dita13.lc.extra-interactions#2]
Eliot's comment: I would not use the prefix "lc" for the specialization as that implies that they are part of the base OASIS-defined interaction set. My normal practice would be to use a different prefix to make the source of the element types clearer. Users could be confused and surprised if they moved to an environment where the specializations are not available and wonder why they no longer have these additional "lc" interactions.

**Comment by birgitstrackenbrock** [comment]
Yes, maybe that's right that "lc" is to much confusing.
We could use "edu"  (from education) or "lce" (lc extra).
We don't want to use a prefix which is connected to the owners, we want one which has to do with the kind of content.
Please, let us know what you thing.

**Comment by devatwork** [comment]
+1 for lce because edu is too generic IMHO.

**Comment by John-Hunt** [comment]
Hi - Add my +1 for lce, no to be confused with ice.

**Comment by birgitstrackenbrock** [comment]
I have changed the prefix to "lce", for all specialized elements.
Now it can easily be seen which element is standaard DITA T&L en which is new.
