### ISSUE TITLE
textEntry

### ISSUE THREAD

**Issue by birgitstrackenbrock** [birgitstrackenbrock/dita13.lc.extra-interactions#7]
Eliot's comment: In the textEntry2 example, could use data or a specialization of data to indicate that a given answer is an alternative correct answer

**Comment by birgitstrackenbrock** [comment]
![image](https://cloud.githubusercontent.com/assets/7901906/14206729/65f12fde-f815-11e5-9895-8df86eae70c5.png)

@contrext Somethink like that?

**Comment by drmacro** [comment]
Yes, that's what I had in mind. 

Note: my main GitHub ID is "drmacro" (contrext works to but I only use it for Contrext-specific stuff which isn't much at the moment).
